/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import model.Project;

public class App {

    public static void main(String[] args) {
    
        ProjectController projectController = new ProjectController();
        Project project = new Project();
        
        
        /* teste projectController.save 
        project.setName("Teste");
        project.setDescription("descricao");
        projectController.save(project);*/
        
        project.setId(3);
        project.setName("teste92");
        project.setDescription("carai");
        projectController.update(project);
        
    }
}
