/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import controller.TaskController;
import model.Project;
import model.Task;
import view.MainScrean;

public class App {

    public static void main(String[] args) {
        
        
    }
}
